quarkus:
  oidc:
    enabled: false
  oidc-client:
    enabled: false
  otel:
    enabled: false
  security:
    auth:
      enabled-in-dev-mode: false

reqour:
  rest:
    app-environment: devel
    reqour-secret-key: devel-secret-dummy-key
    repository-manager-url: https://repository-manager.dev.example.com
    sasl-jaas-conf: config
