reqour-adjuster:
  adjust:
    validate: true
    request: ${ADJUST_REQUEST}
    build-categories:
      STANDARD:
        persistent-mode: PERSISTENT
        temporary-mode: TEMPORARY
        temporary-prefer-persistent-mode: TEMPORARY_PREFER_PERSISTENT
      SERVICE:
        persistent-mode: SERVICE
        temporary-mode: SERVICE_TEMPORARY
        temporary-prefer-persistent-mode: SERVICE_TEMPORARY_PREFER_PERSISTENT
        prefix-of-suffix-version: managedsvc
  maven-executable: mvn
  mdc: ${MDC}
  log:
    final-log-file-path: &final-log-file
      /tmp/file-log.txt

quarkus:
  http:
    enable-compression: true
    enable-decompression: true
  oidc-client:
    auth-server-url: https://keycloak-host/auth/realms/realm # overridden in runtime config
    client-id: sa # overridden in runtime config
    credentials:
      secret: secret-of-sa # overridden in runtime config
  log:
    handler:
      file:
        final-log-file-handler:
          enable: true
          path: *final-log-file
          rotation:
            max-file-size: 10G
          format: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%p] %s%e%n'
    category:
      "org.jboss.pnc._userlog_":
        level: INFO
        handlers:
          - final-log-file-handler
