name: Java Maven build [PR]

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-pr-build.yml@f29f5f54fa71a38e77b3c96c7a6adceac9df361b # main
