name: Java Maven build PR

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-pr-build.yml@31dd704d2c891ac8dd8b45aaae06f347ec2bc4b4 # main
