name: Java Maven build PR

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-pr-build.yml@21150ba868d8999b267c786123bf7a2410a05fc5 # main
